services:
  mapfish-print:
    image: camptocamp/mapfish_print:3.30
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      EXTRA_JARS: /usr/local/tomcat/webapps/ROOT/print-apps/lib
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps

volumes:
  mapfish-print:
