version: '3.4'

services:
  mapfish_print:
    image: camptocamp/mapfish_print:3.27
    ports:
      - 8080:8080
    environment:
      EXTRA_JARS: /usr/local/tomcat/webapps/ROOT/print-apps/lib
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps

volumes:
  mapfish_print:
